 ---

  - hosts: all
    become: yes
    pre_tasks:

    - name: update & upgrade server
      apt:
       update_cache: yes
       upgrade: yes

    - name: set cron job to check uptime of the server every 12am
      cron:
        name: set cron job to check uptime of the server every 12am
        minute: "0" 
        hour: "0"
        day: "*" 
        month: "*" 
        weekday: "*"
        # user: "centos"
        job: "/usr/bin/uptime > /var/log/uptime_check.log 2>&1"
        state: present

       - name: copy the bash script to slave machine
         copy:
           src: laravel-slave.sh
           dest: ~/
           owner: root
           group: root
           mode: 0744

           name: Set and execute permission on the script
           command: chmod +x ~/laravel-slave.sh

           - name: Run Bash script
             command: bash laravel-slave.sh rinsola rinsolaoba < /dev/null